config/routes.rb
GAutomation::Application.routes.draw do

  resources :tc_detail_steps

  resources :wp_dyna_configs

  resources :url_performances 
  
  post "run_url_performance" => "url_performances#run_url_performance", :as=>"url_perform_run"

  get "url_performance_result" => "url_performances#url_performance_result", :as=>"url_performance_result"

  get "result/show_task"
  
  get "result/show_task_result/:task_id"=>"result#show_task_result", :as=>"show_task_result"
  
  get "result/show_tc_result/:testcase_id" => "result#show_tc_result", :as=>"show_tc_result"

  get "upr_delete_all"=>"url_performances#upr_delete_all", :as=>"upr_delete_all"

  get "ajax_result" => "url_performances#ajax_result", :as=>"ajax_result"

  match "search_result_by_counter" => "result#search_result_by_counter", :as=>"search_result_by_counter"

  match "url_showslow_result" => "url_performances#url_showslow_result", :as=>"url_showslow_result"
  
  match "show_wp_run_situ_result" => "result#show_wp_run_situ_result" , :as=>"show_wp_run_situ_result"
  
 match "multi_handle_steps" => "testcases#multi_handle_steps", :as=>"multi_handle_steps"
  
  match "get_refer_objs" => "tobjects#get_refer_objs", :as=>"get_refer_objs"

  resources :teststeps

  resources :tobjects

   resources :wp_dyna_configs

  resources :testcases do
        get 'check_testcase_and_task' , :action=>"check_testcase_and_task"
        get 'update_testcase_tasks', :action=>"update_testcase_tasks", :as=>"update_tt"
        post 'add_relative_tasks',:action=>"add_relative_tasks",:as=>"add_relative_tasks"
        get 'show_steps',:action=>"show_steps",:as=>"show_steps"
        match 'delete_step/:step_id', :action=>"delete_step", :as=>"delete_step"
        match 'destroy_detail_step/:detail_step_id', :action=>"destroy_detail_step", :as=>"destroy_detail_step"
        match 'add_detail_step', :action=>"add_detail_step",:as=>"add_detail_step"
        match "multi_handle_steps" => "testcases#multi_handle_steps", :as=>"multi_handle_steps"
        match  "insert_step/:teststep_id"=> "testcases#insert_step", :as=>"insert_step"
        collection {post :import}
  end

   match 'tasks/:task_id/cancel_related_tc/:testcase_id' => "tasks#cancel_related_tc", :as=> "cancel_related_tc"     
   match 'tasks/:task_id/change_running_status/:testcase_id' => "tasks#change_running_status", :as=> "change_running_status"     
   match "tasks/:task_id/delete_result/:counter/:testcase_id/steps" =>"tasks#delete_steps", :as=>"delete_steps"

  resources :tasks do
          get 'get_relative_testcases', :action=>"get_relative_testcases",:as=>"get_relative_testcases"
          match 'run', :action=>"run",:as=>"run"
          match 'reset', :action=>"reset",:as=>"reset"
          match 'current_result/:counter', :action=>"current_result",:as=>"current_result" 
          match 'current_result/:counter/:testcase_id/steps', :action=>"show_steps", :as=>"show_current_steps"
  end

   match "show_step_detail/:step_detail"=>"tasks#show_step_detail", :as=>"show_step_detail"
   
   match "close_step_detail/:step_id" => "tasks#close_step_detail", :as=>"close_step_detail"
   
   match "show_ajax_result" => "http_result#show_ajax_result", :as=>"show_ajax_result"

   match "search_http" => "http_automations#search_http", :as=>"search_http"
   
   match "url_showslow_period_result" => "result#url_showslow_period_result", :as=>"url_showslow_period_result"

  get "introduction/usinghttp"

  get "introduction/usingfunc"
  
  get "introduction/installation" => "introduction#installation", :as=>"introduction_installation"

  get "http_result/show(/:id)" => "http_result#show"
  
  get "http_result/delete_all" => "http_result#clear_all"
  
  match "http_result/run_http" => "http_result#run_http"
  
  match "show_func_step_result" => "tasks#show_func_step_result", :as=>"show_func_step_result"

  resources :http_automations

  resources :hosts

  resources :remote_machines  do
          get "check",  :action =>"check_machine_situ"
  end

  wiki_root '/wiki'

  get "equip/uploadify"

  get "user_behave/login"

  get "user_behave/logout"

  get "index/index"

  get "index/introduction"
  
  match "search_by_date"=>"url_performances#search_by_date", :as=>"search_by_date"
  
  match "search_by_range_time"=>"url_performances#search_by_range_time", :as=>"search_by_range_time"

  resources :users

 get "user_behave/login" => "user_behave#login", :as=>"login"
 
 post "user_behave/login" => "user_behave#try_login", :as=>"login"
 
 get "user_behave/logout" => "user_behave#logout", :as => "logout"
 
 get "equip/show" => "equip#show"

 match "stop_machine_running_situ/:remote_machine_id" => "remote_machines#stop_machine_running_situ", :as=>"stop_machine_running_situ"

  root :to => 'index#index'

end

app/models/remote_machine.rb
class RemoteMachine < ActiveRecord::Base
  attr_accessible :funcscriptpath, :ipaddress, :smokescriptpath, :comstatus
end

app/controllers/remote_machines_controller.rb
#encoding: utf-8

class RemoteMachinesController < ApplicationController
  # GET /remote_machines
  # GET /remote_machines.json
  def index
    @remote_machines = RemoteMachine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @remote_machines }
    end
  end

  # GET /remote_machines/1
  # GET /remote_machines/1.json
  def show
    @remote_machine = RemoteMachine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @remote_machine }
    end
  end

  # GET /remote_machines/new
  # GET /remote_machines/new.json
  def new
    @remote_machine = RemoteMachine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @remote_machine }
    end
  end

  # GET /remote_machines/1/edit
  def edit
    @remote_machine = RemoteMachine.find(params[:id])
  end

  # POST /remote_machines
  # POST /remote_machines.json
  def create
    @remote_machine = RemoteMachine.new(params[:remote_machine])

    respond_to do |format|
      if @remote_machine.save
        format.html { redirect_to remote_machines_path, notice: 'Remote machine was successfully created.' }
        format.json { render json: @remote_machines, status: :created, location: @remote_machine }
      else
        format.html { render action: "new" }
        format.json { render json: @remote_machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /remote_machines/1
  # PUT /remote_machines/1.json
  def update
    @remote_machine = RemoteMachine.find(params[:id])

    respond_to do |format|
      if @remote_machine.update_attributes(params[:remote_machine])
        format.html { redirect_to @remote_machine, notice: 'Remote machine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @remote_machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remote_machines/1
  # DELETE /remote_machines/1.json
  def destroy
    @remote_machine = RemoteMachine.find(params[:id])
    @remote_machine.destroy

    respond_to do |format|
      format.html { redirect_to remote_machines_url }
      format.json { head :no_content }
    end
  end
  
  STATUS_WRONG = 5
  STATUS_ONLINE = 0
  STATUS_OFFLINE = 3
  STATUS_UNKNOWN = 4
  
  def check_machine_situ
          @remote_machine = RemoteMachine.find(params[:remote_machine_id])
          system("STAF #{@remote_machine.ipaddress} Ping Ping > #{@remote_machine.ipaddress}.log")
          File.exist?("#{@remote_machine.ipaddress}.log") ? nil : @remote_machine.comstatus = STATUS_WRONG 
          if  @remote_machine.ipaddress != STATUS_WRONG
                  ss = ""
                File.open("#{@remote_machine.ipaddress}.log","r"){|f| ss = f.readlines.last.dump}
                if ss.include?("PONG")
                        @remote_machine.comstatus  = STATUS_ONLINE
                else
                        @remote_machine.comstatus  = STATUS_OFFLINE
                end
          end 
          
          if @remote_machine.update_attributes({:comstatus => @remote_machine.comstatus})
                 redirect_to remote_machines_path
         else
                redirect_to remote_machine_path, notice: '不能执行更新操作，请检查相关文件信息！'
         end      
  end
  
  
  def  stop_machine_running_situ
          @remote_machine = RemoteMachine.find(params[:remote_machine_id])
          system("STAF #{@remote_machine.ipaddress} process start command #{@remote_machine.funcscriptpath}/kill.bat")
          @remote_machine.update_attributes({:comstatus => STATUS_UNKNOWN})
          redirect_to remote_machines_path
  end
  
  
  
  
end

app/helpers/remote_machines_helper.rb
module RemoteMachinesHelper
end

app/views/remote_machines/_form.html.erb
<%= form_for(@remote_machine) do |f| %>
  <% if @remote_machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@remote_machine.errors.count, "error") %> prohibited this remote_machine from being saved:</h2>

      <ul>
      <% @remote_machine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">  
  <div class="thumbnail span6 btn-group" style="padding-left: 0;text-align: center">
        <br/>
        <p style="font-family:Kaiti; font-size:25px;"><strong>新增远程机器</strong></p><br/>
        <p class="kt18">机器 <font class="comic"> ip </font>地址  <%= f.text_field :ipaddress %></p>
        <p class="kt18"><font class="comic">HTTP </font>脚本地址  <%= f.text_field :smokescriptpath %></p>
        <p class="kt18">功能脚本地址  <%= f.text_field :funcscriptpath %></p>
        
        <%= f.submit :class=>"btn", :style=>"font-family:Kaiti; font-size:18px", :value=>"确定"%>
        <input type="reset" class="btn" value="重置" style="font-family:Kaiti; font-size:18px">
         <p> <br/></p>
  </div>
  <div class="thumbnail span4 offset1 text-info">
      <br/>
    <p class="kt18">添加说明</p>
     <p class="kt15">需要正确填写 <font class="cm15">ip</font>, 会用相对简单的正则进行匹配</p>
     <p class="kt15">考虑到主机的原因，<font class="cm15">Windows</font>路径分隔符会被转义为 <font class="cm15"> "/" </font></p>
  </div>

  </div>
  

<% end %>

app/views/remote_machines/_header.html.erb
<div class="hero-unit">
    <div class="container">
    <h1 style="font-family: Comic Sans MS; font-size:35px;color:white">Remote Machine</h1>
    <br/>
    <p style="font-family:Kaiti;color:white"> 调控远程机器功能测试与其它类型测试脚本路径</p>
    </div>
</div>

app/views/remote_machines/edit.html.erb
<h1>Editing remote_machine</h1>

<%= render 'form' %>

<%= link_to 'Show', @remote_machine %> |
<%= link_to 'Back', remote_machines_path %>

app/views/remote_machines/index.html.erb
<%= render 'header'%>

<div class="container">
    <div class="thumbnail span11">
            <p class="kt15">机器状态说明：</p>
            <div class="span5">
            <p class="kt15"><font class="comic text-info" style="font-size:15px">Online Free: </font>机器闲置，且可以进行控制</p>
            <p class="kt15"><font class="comic text-warning" style="font-size:15px">HTTP/Function Running: </font>机器正在运行中</p>
            
            </div>
            <div class="span4 offset1">
            <p class="kt15"><font class="comic text-error" style="font-size:15px">Unchecked: </font>未知状态，需要执行检测</p>
            <p class="kt15"><font class="comic text-error" style="font-size:15px">Something Wrong: </font>服务器端异常</p>
            <p class="kt15"><font class="comic text-error"  style="font-size:15px">Offline：</font>离线状态，需要开启机器的<font class="comic"  style="font-size:15px">STAF</font></p>

            </div>
             <div class="span11">
             <p class="kt15">需要添加机器可以点击<%=link_to '这里', new_remote_machine_path%></p>
            </div>
    </div>
</div>
<br/>

<div class="container">
    <div class="thumbnail" style="padding-left:0">
<table class="table">
  <tr style="font-size:16px">
    <th>远程机器地址</th>
    <th>冒烟测试脚本地址</th>
    <th>功能测试脚本地址</th>
    <th>当前状态</th>
  </tr>


<% status_hash = {0=>"Online Free", 1=>"HTTP Running",2=>"Function Running",3=>"Offline", 4=>"Unchecked",5=>"Something Wrong!"}%>
<% status_color = {0 => "text-info", 1=>"text-warning", 2=>"text-warning",3=>"text-error", 4=>"text-error", 5=>"text-error"}%>

<% @remote_machines.each do |remote_machine| %>
  <tr class="cm15">
    <td><%= best_in_place remote_machine, :ipaddress %><%=link_to ' (delete)',remote_machine_path(remote_machine),:method=>:delete, data:{confirm: 'Are you sure?'}%></td>
    <td><%= best_in_place remote_machine, :smokescriptpath %></td>
    <td><%= best_in_place remote_machine, :funcscriptpath %></td>
    <td class="<%= status_color[remote_machine.comstatus]%>"><%= status_hash[remote_machine.comstatus] %>
        <%if  remote_machine.comstatus == 0 or remote_machine.comstatus == 4 or remote_machine.comstatus == 3 or remote_machine.comstatus == 5%>
                <%= link_to '(检查状态)', remote_machine_check_path(remote_machine), :style=>"font-size:15px;font-family:Kaiti"%>
         <%elsif   remote_machine.comstatus == 2%>
            <%= link_to '(终止运行)',  stop_machine_running_situ_path(remote_machine)  ,:style=>"font-size:15px;font-family:Kaiti"%>
        <%end%>
    </td>
  </tr>
<% end %>
</table>
</div>
</div>
<br />

app/views/remote_machines/new.html.erb
<%= render 'header'%>



<%= render 'form' %>

app/views/remote_machines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ipaddress:</b>
  <%= @remote_machine.ipaddress %>
</p>

<p>
  <b>Smokescriptpath:</b>
  <%= @remote_machine.smokescriptpath %>
</p>

<p>
  <b>Funcscriptpath:</b>
  <%= @remote_machine.funcscriptpath %>
</p>




<%= link_to 'Edit', edit_remote_machine_path(@remote_machine) %> |
<%= link_to 'Back', remote_machines_path %>