config/routes.rb
GAutomation::Application.routes.draw do

  resources :tc_detail_steps

  resources :wp_dyna_configs

  resources :url_performances 
  
  post "run_url_performance" => "url_performances#run_url_performance", :as=>"url_perform_run"

  get "url_performance_result" => "url_performances#url_performance_result", :as=>"url_performance_result"

  get "result/show_task"
  
  get "result/show_task_result/:task_id"=>"result#show_task_result", :as=>"show_task_result"
  
  get "result/show_tc_result/:testcase_id" => "result#show_tc_result", :as=>"show_tc_result"

  get "upr_delete_all"=>"url_performances#upr_delete_all", :as=>"upr_delete_all"

  get "ajax_result" => "url_performances#ajax_result", :as=>"ajax_result"

  match "search_result_by_counter" => "result#search_result_by_counter", :as=>"search_result_by_counter"

  match "url_showslow_result" => "url_performances#url_showslow_result", :as=>"url_showslow_result"
  
  match "show_wp_run_situ_result" => "result#show_wp_run_situ_result" , :as=>"show_wp_run_situ_result"
  
 match "multi_handle_steps" => "testcases#multi_handle_steps", :as=>"multi_handle_steps"
  
  match "get_refer_objs" => "tobjects#get_refer_objs", :as=>"get_refer_objs"

  resources :teststeps

  resources :tobjects

   resources :wp_dyna_configs

  resources :testcases do
        get 'check_testcase_and_task' , :action=>"check_testcase_and_task"
        get 'update_testcase_tasks', :action=>"update_testcase_tasks", :as=>"update_tt"
        post 'add_relative_tasks',:action=>"add_relative_tasks",:as=>"add_relative_tasks"
        get 'show_steps',:action=>"show_steps",:as=>"show_steps"
        match 'delete_step/:step_id', :action=>"delete_step", :as=>"delete_step"
        match 'destroy_detail_step/:detail_step_id', :action=>"destroy_detail_step", :as=>"destroy_detail_step"
        match 'add_detail_step', :action=>"add_detail_step",:as=>"add_detail_step"
        match "multi_handle_steps" => "testcases#multi_handle_steps", :as=>"multi_handle_steps"
        match  "insert_step/:teststep_id"=> "testcases#insert_step", :as=>"insert_step"
        collection {post :import}
  end

   match 'tasks/:task_id/cancel_related_tc/:testcase_id' => "tasks#cancel_related_tc", :as=> "cancel_related_tc"     
   match 'tasks/:task_id/change_running_status/:testcase_id' => "tasks#change_running_status", :as=> "change_running_status"     
   match "tasks/:task_id/delete_result/:counter/:testcase_id/steps" =>"tasks#delete_steps", :as=>"delete_steps"

  resources :tasks do
          get 'get_relative_testcases', :action=>"get_relative_testcases",:as=>"get_relative_testcases"
          match 'run', :action=>"run",:as=>"run"
          match 'reset', :action=>"reset",:as=>"reset"
          match 'current_result/:counter', :action=>"current_result",:as=>"current_result" 
          match 'current_result/:counter/:testcase_id/steps', :action=>"show_steps", :as=>"show_current_steps"
  end

   match "show_step_detail/:step_detail"=>"tasks#show_step_detail", :as=>"show_step_detail"
   
   match "close_step_detail/:step_id" => "tasks#close_step_detail", :as=>"close_step_detail"
   
   match "show_ajax_result" => "http_result#show_ajax_result", :as=>"show_ajax_result"

   match "search_http" => "http_automations#search_http", :as=>"search_http"
   
   match "url_showslow_period_result" => "result#url_showslow_period_result", :as=>"url_showslow_period_result"

  get "introduction/usinghttp"

  get "introduction/usingfunc"
  
  get "introduction/installation" => "introduction#installation", :as=>"introduction_installation"

  get "http_result/show(/:id)" => "http_result#show"
  
  get "http_result/delete_all" => "http_result#clear_all"
  
  match "http_result/run_http" => "http_result#run_http"
  
  match "show_func_step_result" => "tasks#show_func_step_result", :as=>"show_func_step_result"

  resources :http_automations

  resources :hosts

  resources :remote_machines  do
          get "check",  :action =>"check_machine_situ"
  end

  wiki_root '/wiki'

  get "equip/uploadify"

  get "user_behave/login"

  get "user_behave/logout"

  get "index/index"

  get "index/introduction"
  
  match "search_by_date"=>"url_performances#search_by_date", :as=>"search_by_date"
  
  match "search_by_range_time"=>"url_performances#search_by_range_time", :as=>"search_by_range_time"

  resources :users

 get "user_behave/login" => "user_behave#login", :as=>"login"
 
 post "user_behave/login" => "user_behave#try_login", :as=>"login"
 
 get "user_behave/logout" => "user_behave#logout", :as => "logout"
 
 get "equip/show" => "equip#show"

 match "stop_machine_running_situ/:remote_machine_id" => "remote_machines#stop_machine_running_situ", :as=>"stop_machine_running_situ"

  root :to => 'index#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :run_counter
  has_many :tcandtask, :dependent=>:destroy
end

app/controllers/tasks_controller.rb
#encoding: utf-8

class TasksController < ApplicationController
  
  
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @remote_machines = RemoteMachine.where(["comstatus = ?",0])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
        
    respond_to do |format|
            if @task.save
      format.html {redirect_to tasks_path}# new.html.erb
      format.json { render json: @task }
      else
        format.html {redirect_to tasks_path, notice: '添加失败'}
    end
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
  
  def get_relative_testcases
          @task = Task.find(params[:task_id])
          @testcases = []
          Tcandtask.where(["task_id = ?",params[:task_id]]).each do |tcatk|
                  @testcases << Testcase.find(tcatk.testcase_id)
          end
  end
  
  
  HTTP_RUNNING_STATUS = 2
  
  def run
          @remote_machine = RemoteMachine.find(params[:remote_machine])
          @testcases = ""
          tcandtks = Tcandtask.where(["task_id = ?",params[:task_id]])
          tcandtks.each_with_index do |tcatk,id|
                  if tcandtks.length-1 == id
                          @testcases = @testcases+"#{tcatk.testcase_id}"
                  else
                          @testcases = @testcases+"#{tcatk.testcase_id},"
                  end
          end
         @task = Task.find(params[:task_id])
         system("staf  #{@remote_machine.ipaddress} var set shared var task_id=#{@task.id}") 
          system("staf #{@remote_machine.ipaddress} var set shared var task_counter=#{@task.run_counter+1}")
          system("staf #{@remote_machine.ipaddress} var set shared var testcases=#{@testcases}")
          system("staf  #{@remote_machine.ipaddress} process start command #{@remote_machine.funcscriptpath}/run.bat ")
        @remote_machine.update_attributes({:comstatus => HTTP_RUNNING_STATUS})

        @task.update_attributes({:run_counter=>@task.run_counter+1})
        redirect_to task_current_result_path(@task,@task.run_counter)
  end
  
  def reset
          @task = Task.find(params[:task_id])
          @task.update_attributes({:run_counter=> 0})
          TestcaseResult.delete_all(["task_id = ?",params[:task_id]])
          StepResult.delete_all(["task_id = ?", params[:task_id]])
          redirect_to tasks_path
  end
  
  def current_result
                @task = Task.find(params[:task_id])
                @testcases_result = TestcaseResult.where(["counter = ? and task_id = ?", params[:counter].to_i, @task.id])
  end
  
  def show_steps
          @task = Task.find(params[:task_id])
          @testcase_result = TestcaseResult.find(params[:testcase_id])
          @testcase = Testcase.find(@testcase_result.testcase_id)
          @steps_result = StepResult.where(["task_id = ? and counter = ? and testcase_id = ?",params[:task_id],params[:counter],@testcase.id])
  end
  
  def show_step_detail
        @step = Teststep.find(params[:step_detail])
  end
  
  def close_step_detail
          @step = params[:step_id]
  end
  
  def show_func_step_result
          @task = Task.find(params[:task_id])
          @testcase_result = TestcaseResult.find(params[:testcase_id])
          @testcase = Testcase.find(@testcase_result.testcase_id)
          @steps_result = StepResult.where(["task_id = ? and counter = ? and testcase_id = ?",params[:task_id],params[:counter],@testcase.id])
          respond_to do |format|
                  format.js
          end
  end
  
  def   cancel_related_tc
            Tcandtask.delete_all(["task_id = ? and testcase_id = ?", params[:task_id], params[:testcase_id]])
           redirect_to task_get_relative_testcases_path(params[:task_id])
  end
  
  def   change_running_status
          tc = Testcase.find(params[:testcase_id])
          if  tc.run == 1
                  tc.update_attributes(:run=>0)
          else
                  tc.update_attributes(:run=>1)
          end
          redirect_to task_get_relative_testcases_path(params[:task_id])
  end
  
  def   delete_steps
          TestcaseResult.delete_all(["counter = ? and testcase_id = ? and task_id = ?", params[:counter], params[:testcase_id],params[:task_id]])
          StepResult.delete_all(["counter = ? and testcase_id = ? and task_id = ?", params[:counter], params[:testcase_id], params[:task_id]])
          redirect_to   show_task_result_path(params[:task_id])
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :run_counter %><br />
    <%= f.number_field :run_counter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_header.html.erb
<div class="hero-unit">
    <div class="container">
    <h1 style="font-family: Comic Sans MS; font-size:35px;color:white">Task</h1>
    <br/>
    <p style="font-family:Kaiti;color:white"> 模块化执行测试任务</p>
    </div>
</div>

app/views/tasks/_result_header.html.erb
<div class="hero-unit">
    <div class="container">
    <h1 style="font-family: Comic Sans MS; font-size:35px;color:white">Task</h1>
    <br/>
    <p style="font-family:Kaiti;color:white"> 模块化执行测试任务</p>
    </div>
</div>

app/views/tasks/_step_result.html.erb
<%color={0=>"text-success", 1=>"text-warning", 2=>"text-error", nil=>""} %>
<% result={0=>"PASS", 1=>"FAIL", 2=>"ERROR", nil=> ""}%>
<tr class="cm15">
             <td><%= step_result.ipaddress%></td>
             <td class="<%= color[step_result.result]%>"><%= result[step_result.result]%></td>
             <td><%= step_result.actual.gsub(/(.{30})/,"\\1<br/>").html_safe %></td>
             <td><%= step_result.screenshot_path.gsub(/(.{30})/,"\\1<br/>").html_safe%></td>
             <td id="show_step_<%= step_result.teststep_id%>"><%= link_to "Show Step", show_step_detail_path(step_result.teststep_id) ,:remote=>true%></td>
</tr>
<tr id="info_detail<%= step_result.teststep_id%>"></tr>

app/views/tasks/close_step_detail.js.erb
$('#show_step_<%= @step%>').html('<%= link_to "Show Step", show_step_detail_path(@step) ,:remote=>true%>')
$('#info_detail<%=@step%>').html("")

app/views/tasks/current_result.html.erb
<%= render 'header'%>

<div class="container">
    <div class="thumbnail">
        <br/>
        <p class="kt18"> 当前关联的测试用例</p>
    </div>
</div>
<br/>

<div class="container">
    <div class="thumbnail span11">
        <div class="span11">
        <br/>
        <p class="kt18">已完成用例结果汇总：</p>
        <%pass,fail,error,other=0,0,0,0%>
                    <% @testcases_result.each do |tc|%>
                           <% case tc.result%>
                           <% when 0%>
                                <% pass = pass + 1%>
                           <% when 1%>
                                <% fail = fail+ 1%>
                           <% when 2%>
                                <% error = error+1%>
                           <%else%>
                                <% other = other+1%>         
                                <%end%>      
                    <% end %>
                    </div>
         <p >
             <div class="span2"><font class="cm15 text-success"  >PASS：<%= pass%>  </font></div>
             <div class="span2"><font class="cm15 text-warning">FAIL：<%= fail%>  </font></div>
             <div class="span2"><font class="cm15 text-error">ERROR：<%= error%>  </font></div>  
       </p>  
         
    </div>
</div>

<br/>
<% result={0=>"PASS", 1=>"FAIL", 2=>"ERROR", nil=> ""}%>
<%status_situ = {0=>"UnKnown", 1=>"Running", 2=>"Error", 3=>"Finish"}%>
<% status={0=> "text-warning", 1=>"text-info", 2=>"text-error", 3=>"text-info"}%>
<%color={0=>"text-success", 1=>"text-warning", 2=>"text-error", nil=>""} %>

<div class="container">
    <div class="thumbnail" style="padding-left:0">
        <table class="table">
            
        <tr>
            <th  style="font-family: Comic Sans MS; font-size:16px;">Name</th>
            <th  style="font-family: Comic Sans MS; font-size:16px;">Status</th>
            <th style="font-family:Comic Sans MS; font-size:16px">Result</th>
            <th style="font-family:Comic Sans MS; font-size:16px">Machine</th>
            <th style="font-family:Comic Sans MS; font-size:16px">FinishTime</th>
        </tr>
        

                <%@testcases_result.each do |tr|%>
                   <tr class="cm15">
                       <td><%= link_to tr.testcase_id%></td>
                       <td class="<%= status[tr.status]%>"><%= status_situ[tr.status]%></td>
                       <td class="<%= color[tr.result]%>"><%= result[tr.result]%></td>
                       <td><%= tr.ipaddress%></td>
                       <td><%= tr.updated_at%></td>
                       <td><%= link_to "Show Steps", task_show_current_steps_path(params[:task_id],params[:counter],tr.id)%></td>
                   </tr>
                <%end%>

        
         </table>
    </div>
</div>
<br/>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/get_relative_testcases.js.erb
str = "";

str = "<p class='kt18  text-info'  ><%= @task.description%></p>"

<% obj = {1=>"运行", 0=>"不运行"} %>

<% @testcases.each do |tc| %>
        str = str + "<p class='kt18'><font class='cm15'><%=j link_to  tc.name, testcase_show_steps_path(tc)%>:</font> <%= tc.description%> <font> <font class='text-info'> 状态：</font><%= obj[tc.run]%><%=j link_to '(修改)', change_running_status_path(@task.id, tc.id), :remote=>true%></font> <font> <%=j link_to '取消关联' , cancel_related_tc_path(@task.id, tc.id), :remote=>true   %></font></p>";
<%end%>

$('#tkandtc').html(str);

app/views/tasks/index.html.erb
<%= render 'header'%>

<div class="container">
    <div class="thumbnail">
            <br/>
             <p class="kt18"> 添加新任务可以点击<%= link_to "这里", new_task_path%></p>
    </div>
</div>
<br/ >
<div class="container">
    <div class="thumbnail">
        <br/>
        <div id="tkandtc"><p class="kt18">未选择任何任务</p></div>
    </div>
</div>
<br/>


<div class="container">
    <div class="thumbnail" style="padding-left:0">
<table class="table">
  <tr>
    <th style="font-family: Comic Sans MS;font-size:16px;">Description</th>
    <th style="font-family: Comic Sans MS;font-size:16px;">Counter</th>
    <th  style="font-family: Comic Sans MS;font-size:16px;">Machine</th>
    <th  style="font-family: Comic Sans MS;font-size:16px; text-align: center"  colspan="3">Action</th>
  </tr>


<% @tasks.each do |task| %>
<%= form_tag(task_run_path(task)) do %>
  <tr class="cm15">
    <td  style="font-family:Kaiti"><%=best_in_place task,:description ,:html_attrs=>{ :style=>"width:60px;font-family: Kaiti"}%></td>
    <td><%= best_in_place task,:run_counter ,:html_attrs=>{ :style=>"width:15px;font-family: Kaiti"}%><%= link_to '(Reset)', task_reset_path(task), data: {confirm:'Are you sure?'}%></td>
    <td><%= select_tag "remote_machine", options_from_collection_for_select(@remote_machines,"id","ipaddress"),:style=>"font-family:Comic Sans MS"%> </td>
    <td><%= link_to 'Show Relative TCs',task_get_relative_testcases_path(task),:remote=>true%></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><input type="submit" value="运行任务" style="font-family:Kaiti" class="btn btn-primary"/></td>
 <%end%>
  </tr>
<% end %>
</table>


    </div>
</div>
<br />

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Run counter:</b>
  <%= @task.run_counter %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/show_func_step_result.js.erb
<%= render partial: "step_result", collection: @steps_result%>

app/views/tasks/show_step_detail.js.erb
<% if @step%>

$('#show_step_<%=@step.id%>').html('<%= link_to "Close Step", close_step_detail_path(@step), :remote=>true %>')

str ="";

str = str + '<td colspan="6"  class="text-info"  style="line-height: 180%"><p><div class="span5"> <font style="font-family: Kaiti;font-size:16px">描述信息：<%= @step.description%></font> </div>';

str = str + '<div class="span4 offset1"><font style="font-family: Kaiti;font-size:16px">执行操作：</font><font class="cm15"> <%= @step.step_method%></font></div>'

str = str + '<div class="span5"><font style="font-family: Kaiti;font-size:16px">元素名称：</font><font class="cm15"><%= @step.obj_name%></font></div>'

str = str + '<div class="span4 offset1"><font style= "font-family:Kaiti;font-size:16px">执行方法：</font><font class="cm15"><%= @step.call_method%></font></div>'

str = str + '<div class="span5"><font style="font-family: Kaiti;font-size:16px">输入：</font><font class="cm15"><%= @step.input%></font></div>'

str = str + '<div class="span4 offset1"><font style= "font-family:Kaiti;font-size:16px">输出：</font><font class="cm15"><%= @step.expect%></font></div>'


str = str + "</p></td>";



$('#info_detail<%= @step.id%>').html(str);

$('#info_detail<%= @step.id%>').css({'background-color':'rgb(240, 240, 240)'})
<%end%>

app/views/tasks/show_steps.html.erb
<%= render 'result_header'%>

<% situ_env = {"ff"=>"FireFox", "chrome"=>"Chrome", "ie"=>"Internet Explorer"}%>



<div class="container">
    <div class="thumbnail">
                <br/>
                <p class="kt18">当前运行任务名称：<%= @task.description%></p>
                <p class="kt18">当前运行步骤名称：<font class="cm15"><%= link_to @testcase.name, testcase_show_steps_path(@testcase)%></font><font style="font-size:15px;color:gray">(点击查看用例步骤详情)</font></p>
                <p class="kt18">步骤描述信息：<%= @testcase.description%></p>
                <p class="kt18">运行环境：<font class="cm15"><%= situ_env[@testcase.browser]%></font></p>

    </div>
</div>
<br/>

<input type="hidden" value="<%= params[:task_id]%>" id="js_task_id">
<input type="hidden" value="<%= params[:testcase_id]%>" id="js_testcase_id">
<input type="hidden" value="<%= params[:counter]%>" id="js_counter">


<div class="container">
    <div class="thumbnail" style="padding-left:0">
            <table class="table">
                        <tr>
                            <td style="font-family:Comic Sans MS; font-size:16px">Machine</td>
                            <td style="font-family:Comic Sans MS;font-size:16px">Result</td>
                            <td style="font-family:Comic Sans MS;font-size:16px">Actual</td>
                            <td style="font-family:Comic Sans MS;font-size:16px">ImagePath</td>
                        </tr>
    
                        <%if  @testcase_result.status != 3%>
                        <tbody id="func_result_ajax">
                            <%else%>
                            <tbody>
                            <%end%>                        
                                <%= render partial: "step_result", collection: @steps_result%>
                        </tbody>
            </table>
    </div>
</div>
<br/>