config/routes.rb
GAutomation::Application.routes.draw do

  resources :tc_detail_steps

  resources :wp_dyna_configs

  resources :url_performances 
  
  post "run_url_performance" => "url_performances#run_url_performance", :as=>"url_perform_run"

  get "url_performance_result" => "url_performances#url_performance_result", :as=>"url_performance_result"

  get "result/show_task"
  
  get "result/show_task_result/:task_id"=>"result#show_task_result", :as=>"show_task_result"
  
  get "result/show_tc_result/:testcase_id" => "result#show_tc_result", :as=>"show_tc_result"

  get "upr_delete_all"=>"url_performances#upr_delete_all", :as=>"upr_delete_all"

  get "ajax_result" => "url_performances#ajax_result", :as=>"ajax_result"

  match "search_result_by_counter" => "result#search_result_by_counter", :as=>"search_result_by_counter"

  match "url_showslow_result" => "url_performances#url_showslow_result", :as=>"url_showslow_result"
  
  match "show_wp_run_situ_result" => "result#show_wp_run_situ_result" , :as=>"show_wp_run_situ_result"
  
 match "multi_handle_steps" => "testcases#multi_handle_steps", :as=>"multi_handle_steps"
  
  match "get_refer_objs" => "tobjects#get_refer_objs", :as=>"get_refer_objs"

  resources :teststeps

  resources :tobjects

   resources :wp_dyna_configs

  resources :testcases do
        get 'check_testcase_and_task' , :action=>"check_testcase_and_task"
        get 'update_testcase_tasks', :action=>"update_testcase_tasks", :as=>"update_tt"
        post 'add_relative_tasks',:action=>"add_relative_tasks",:as=>"add_relative_tasks"
        get 'show_steps',:action=>"show_steps",:as=>"show_steps"
        match 'delete_step/:step_id', :action=>"delete_step", :as=>"delete_step"
        match 'destroy_detail_step/:detail_step_id', :action=>"destroy_detail_step", :as=>"destroy_detail_step"
        match 'add_detail_step', :action=>"add_detail_step",:as=>"add_detail_step"
        match "multi_handle_steps" => "testcases#multi_handle_steps", :as=>"multi_handle_steps"
        match  "insert_step/:teststep_id"=> "testcases#insert_step", :as=>"insert_step"
        collection {post :import}
  end

   match 'tasks/:task_id/cancel_related_tc/:testcase_id' => "tasks#cancel_related_tc", :as=> "cancel_related_tc"     
   match 'tasks/:task_id/change_running_status/:testcase_id' => "tasks#change_running_status", :as=> "change_running_status"     
   match "tasks/:task_id/delete_result/:counter/:testcase_id/steps" =>"tasks#delete_steps", :as=>"delete_steps"

  resources :tasks do
          get 'get_relative_testcases', :action=>"get_relative_testcases",:as=>"get_relative_testcases"
          match 'run', :action=>"run",:as=>"run"
          match 'reset', :action=>"reset",:as=>"reset"
          match 'current_result/:counter', :action=>"current_result",:as=>"current_result" 
          match 'current_result/:counter/:testcase_id/steps', :action=>"show_steps", :as=>"show_current_steps"
  end

   match "show_step_detail/:step_detail"=>"tasks#show_step_detail", :as=>"show_step_detail"
   
   match "close_step_detail/:step_id" => "tasks#close_step_detail", :as=>"close_step_detail"
   
   match "show_ajax_result" => "http_result#show_ajax_result", :as=>"show_ajax_result"

   match "search_http" => "http_automations#search_http", :as=>"search_http"
   
   match "url_showslow_period_result" => "result#url_showslow_period_result", :as=>"url_showslow_period_result"

  get "introduction/usinghttp"

  get "introduction/usingfunc"
  
  get "introduction/installation" => "introduction#installation", :as=>"introduction_installation"

  get "http_result/show(/:id)" => "http_result#show"
  
  get "http_result/delete_all" => "http_result#clear_all"
  
  match "http_result/run_http" => "http_result#run_http"
  
  match "show_func_step_result" => "tasks#show_func_step_result", :as=>"show_func_step_result"

  resources :http_automations

  resources :hosts

  resources :remote_machines  do
          get "check",  :action =>"check_machine_situ"
  end

  wiki_root '/wiki'

  get "equip/uploadify"

  get "user_behave/login"

  get "user_behave/logout"

  get "index/index"

  get "index/introduction"
  
  match "search_by_date"=>"url_performances#search_by_date", :as=>"search_by_date"
  
  match "search_by_range_time"=>"url_performances#search_by_range_time", :as=>"search_by_range_time"

  resources :users

 get "user_behave/login" => "user_behave#login", :as=>"login"
 
 post "user_behave/login" => "user_behave#try_login", :as=>"login"
 
 get "user_behave/logout" => "user_behave#logout", :as => "logout"
 
 get "equip/show" => "equip#show"

 match "stop_machine_running_situ/:remote_machine_id" => "remote_machines#stop_machine_running_situ", :as=>"stop_machine_running_situ"

  root :to => 'index#index'

end

app/models/http_automation.rb
class HttpAutomation < ActiveRecord::Base
  attr_accessible :base_id, :description, :env, :expect, :host_id, :hre_type, :url_path
end

app/controllers/http_automations_controller.rb
class HttpAutomationsController < ApplicationController
  # GET /http_automations
  # GET /http_automations.json
  def index
    @http_automations = HttpAutomation.all
    @hosts = Host.all
              @remote_machines = RemoteMachine.where(["comstatus = ?",0])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @http_automations }
    end
  end

  # GET /http_automations/1
  # GET /http_automations/1.json
  def show
    @http_automation = HttpAutomation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @http_automation }
    end
  end

  # GET /http_automations/new
  # GET /http_automations/new.json
  def new
    @http_automation = HttpAutomation.new

    respond_to do |format|
            if @http_automation.save
      format.html {redirect_to http_automations_url}# new.html.erb
      format.json { render json: @http_automation }
      end
    end
  end

  # GET /http_automations/1/edit
  def edit
    @http_automation = HttpAutomation.find(params[:id])
  end

  # POST /http_automations
  # POST /http_automations.json
  def create
    @http_automation = HttpAutomation.new(params[:http_automation])

    respond_to do |format|
      if @http_automation.save
        format.html { redirect_to @http_automation, notice: 'Http automation was successfully created.' }
        format.json { render json: @http_automation, status: :created, location: @http_automation }
      else
        format.html { render action: "new" }
        format.json { render json: @http_automation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /http_automations/1
  # PUT /http_automations/1.json
  def update
    @http_automation = HttpAutomation.find(params[:id])

    respond_to do |format|
      if @http_automation.update_attributes(params[:http_automation])
        format.html { redirect_to @http_automation, notice: 'Http automation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @http_automation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /http_automations/1
  # DELETE /http_automations/1.json
  def destroy
    @http_automation = HttpAutomation.find(params[:id])
    @http_automation.destroy

    respond_to do |format|
      format.html { redirect_to http_automations_url }
      format.json { head :no_content }
    end
  end
  
  def search_http
          host_id = params[:host_id].to_i
          env_id = params[:env_id].gsub(/\((.*)\)/, "").to_i
          if host_id == 0
                  if env_id == 0
                          @http_automations = HttpAutomation.all
                   else
                           @http_automations = HttpAutomation.where(["env= ? ",env_id])       
                  end
         else
                if env_id == 0
                        @http_automations = HttpAutomation.where(["host_id = ?", host_id])
                else
                        @http_automations = HttpAutomation.where(["env= ? and host_id = ?", env_id, host_id])
                end                 
          end
          respond_to do |format|
                  format.js
          end
  end
  
end

app/helpers/http_automations_helper.rb
module HttpAutomationsHelper
end

app/views/http_automations/_form.html.erb
<div class="container">
    <div class="thumbnail span6" style="padding-left:0; text-align:center">
    <br/>
    <p class="kt18"><strong>添加 <font class="comic"> http </font> 测试步骤</strong></p>
        
<br/>

<%= form_for(@http_automation) do |f| %>

    <p class="kt18"><font class="comic">http </font>类型：<%= f.text_field :hre_type%></p>
    <p class="kt18">步骤描述：<%= f.text_field :description%></p>
    <p class="kt18">依赖用例：<%= f.text_field :base_id%></p>
    <p class="kt18">预期结果：<%= f.text_field :expect%></p>
    <p class="kt18">关联<font class="comic"> host</font>: <%= f.text_field :host_id%></p>
    <p class="kt18">所处环境：<%= f.text_field :env%></p>
    <p class="kt18">完整<font class="comic">url</font>: <%= f.text_field :url_path%></p>
  <div class="actions">
    <%= f.submit :class=>"btn", :value=>"确认添加", :style=>"font-family: Kaiti"%>
  </div>
<% end %>
</div>

<div class="thumbnail offset1 span4 text-info">
    <br/>
    <p class="kt18">说明信息:</p>
    <p class="kt15">预期结果针对<font class="cm15">json </font>返回值</p>
    <p class="kt15">全部文本框内容都可以在<font class="cm15">http</font>测试页修改(建议)</p>
    <p class="kt15">关联用<font class="cm15"> '>' </font>分割</p>
</div>
</div>

app/views/http_automations/_header.html.erb
<div class="hero-unit">
    <div class="container">
    <h1 style="font-family: Comic Sans MS; font-size:35px;color:white">HTTP Automation</h1>
    <br/>
    <p style="font-family:Kaiti;color:white"><font class="comic">Http </font>验证步骤的调整，需要注意关联方式的书写</p>
    </div>
</div>

app/views/http_automations/_http_automation.html.erb
  <tr class="cm15">
      <td><%= best_in_place  http_automation, :id%></td>
    <td><%= best_in_place  http_automation,:hre_type ,:html_attrs=>{ :style=>"width:20px;"}%></td>
    <td style="font-family: Kaiti; font-size:15px"><%=best_in_place  http_automation,:description ,:html_attrs=>{ :style=>"width:30px;font-family: Kaiti"}%></td>
    <td><%=best_in_place http_automation,:base_id ,:html_attrs=>{ :style=>"width:10px;font-family: Comic Sans MS"}%></td>
    <td><%=best_in_place http_automation,:expect , :display_with=>lambda{|v| v.gsub(/(.{20})/,"\\1<br/>").html_safe},:html_attrs=>{ :style=>"width:30px;font-family: Comic Sans MS"}%></td>
    <td>
        <%=best_in_place http_automation,:host_id ,:html_attrs=>{ :style=>"width:40px;"}%>
    </td>
    <td><%=best_in_place http_automation,:env ,:html_attrs=>{ :style=>"width:10px;"}%></td>
    <td><%= best_in_place  http_automation,:url_path, :display_with=>lambda{|v| v.gsub(/(.{25})/,"\\1<br/>").html_safe} ,:html_attrs=>{ :style=>"width:105px;font-family: Comic Sans MS"}%></td>
    <td><%= link_to "Destroy", http_automation, method: :delete, data: { confirm: "Are you sure?" } %></td>
    
  </tr>

app/views/http_automations/edit.html.erb
<h1>Editing http_automation</h1>

<%= render 'form' %>

<%= link_to 'Show', @http_automation %> |
<%= link_to 'Back', http_automations_path %>

app/views/http_automations/index.html.erb
<%= render 'header'%>

<div class="container">
    <div class="thumbnail">
        <br/>
            <p class="kt18">当前可用的<font class="comic">host: </font>(新增点击<%= link_to '这里', new_host_path%>)</p>
            <% @hosts.each  do |host|%>
                  
                    <% if  host.id % 4 == 1 %>
                           <p> <font class="comic"><%= host.id%>: <font class="text-info"><%= host.url%></font></font>  &nbsp;
                    <% elsif  host.id % 4 != 0%>
                        <font class="comic"><%= host.id%>: <font class="text-info"><%= host.url%></font></font>&nbsp;
                    <% else %>
                        <font class="comic"><%= host.id%>:<font class="text-info"><%= host.url%></font></font></p>    
                    <% end %>
            <% end %>
        <br/>
        <p class="kt18"> <font class="comic">Env </font>默认值：</p>
        <p class="kt18"><font class="comic">1: gomeprelive;   2: atgsit ; 3: atguat</font></p>
        <br/>
        <p class="kt18">创建新的<font class="comic"> http </font>测试步骤，点击<%= link_to '这里', new_http_automation_path%></p>
        
    </div>
</div>
<br/>

<div class="container">
    <div class="thumbnail span6">
            <br/>
            <%= form_tag(http_result_run_http_path)  do %>
            <p class="kt18">选择执行条件：</p>
            <p class="kt18">
                机器：<%= select_tag "remote_machine", options_from_collection_for_select(@remote_machines,"id","ipaddress"),:style=>"font-family:Comic Sans MS"%> <br/>
                环境:  <%= select_tag "cur_env", "<option>0(all)</option><option>1(gomeprelive)</option><option>2(atgsit)</option><option>3(atguat)</option><option>4(others)</option>".html_safe,:style=>"font-family:Comic Sans MS"%> 
            </p>
            <p><input type="submit" style="font-family:Kaiti;font-size:15px" class="btn btn-primary" value="执行操作"/></p>
            <% end %>
    </div>
    
    <div class="thumbnail span5">
             <%= form_tag(search_http_path, :remote=>true)  do%>
             <br/>
             <p class="kt18">选择搜索条件</p>
                 <p class="kt18">    
                     环境:  <%= select_tag "env_id", "<option>0(all)</option><option>1(gomeprelive)</option><option>2(atgsit)</option><option>3(atguat)</option><option>4(others)</option>".html_safe,:style=>"font-family:Comic Sans MS"%>
                     <br/> 
                    <font class="comic">Host:  </font><%= select_tag "host_id",options_from_collection_for_select(@hosts, "id", "url"), :style=>"font-family:Comic Sans MS", prompt: "From All"%>
                </p>
                <p><input type="submit" style="font-family:Kaiti;font-size:15px" class="btn btn-primary" value="搜索"/></p>
             <%end%>
   </div>
</div>


<br/>
<div class="container">
    <div class="thumbnail span11"  style="padding-left:0px">
<table class="table">
  <tr>
      <th  style="font-family: Comic Sans MS; font-size:18px;">ID</th>
    <th  style="font-family: Comic Sans MS; font-size:18px;">Hre type</th>
    <th  style="font-family: Comic Sans MS; font-size:18px;">Description</th>
    <th  style="font-family: Comic Sans MS; font-size:18px;">Base</th>
    <th  style="font-family: Comic Sans MS; font-size:18px;">Expect</th>
    <th  style="font-family: Comic Sans MS; font-size:18px;">Host</th>
    <th  style="font-family: Comic Sans MS; font-size:18px;">Env</th>
    <th  style="font-family: Comic Sans MS; font-size:18px;">Url path</th>
    <th></th>

  </tr>

    <tbody id="search_http">
      <%= render partial: 'http_automation', collection: @http_automations%>
   </tbody>
</table>
<br/>
    </div>

</div>

<br />

app/views/http_automations/new.html.erb
<%= render 'header'%>

<%= render 'form' %>

<br/>

app/views/http_automations/search_http.js.erb
$('#search_http').html('<%=j render partial: 'http_automation', collection: @http_automations%>');

app/views/http_automations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hre type:</b>
  <%= @http_automation.hre_type %>
</p>

<p>
  <b>Description:</b>
  <%= @http_automation.description %>
</p>

<p>
  <b>Base:</b>
  <%= @http_automation.base_id %>
</p>

<p>
  <b>Expect:</b>
  <%= @http_automation.expect %>
</p>

<p>
  <b>Host:</b>
  <%= @http_automation.host_id %>
</p>

<p>
  <b>Env:</b>
  <%= @http_automation.env %>
</p>

<p>
  <b>Url path:</b>
  <%= @http_automation.url_path %>
</p>


<%= link_to 'Edit', edit_http_automation_path(@http_automation) %> |
<%= link_to 'Back', http_automations_path %>