config/routes.rb
GAutomation::Application.routes.draw do

  resources :tc_detail_steps

  resources :wp_dyna_configs

  resources :url_performances 
  
  post "run_url_performance" => "url_performances#run_url_performance", :as=>"url_perform_run"

  get "url_performance_result" => "url_performances#url_performance_result", :as=>"url_performance_result"

  get "result/show_task"
  
  get "result/show_task_result/:task_id"=>"result#show_task_result", :as=>"show_task_result"
  
  get "result/show_tc_result/:testcase_id" => "result#show_tc_result", :as=>"show_tc_result"

  get "upr_delete_all"=>"url_performances#upr_delete_all", :as=>"upr_delete_all"

  get "ajax_result" => "url_performances#ajax_result", :as=>"ajax_result"

  match "search_result_by_counter" => "result#search_result_by_counter", :as=>"search_result_by_counter"

  match "url_showslow_result" => "url_performances#url_showslow_result", :as=>"url_showslow_result"
  
  match "show_wp_run_situ_result" => "result#show_wp_run_situ_result" , :as=>"show_wp_run_situ_result"
  
 match "multi_handle_steps" => "testcases#multi_handle_steps", :as=>"multi_handle_steps"
  
  match "get_refer_objs" => "tobjects#get_refer_objs", :as=>"get_refer_objs"

  resources :teststeps

  resources :tobjects

   resources :wp_dyna_configs

  resources :testcases do
        get 'check_testcase_and_task' , :action=>"check_testcase_and_task"
        get 'update_testcase_tasks', :action=>"update_testcase_tasks", :as=>"update_tt"
        post 'add_relative_tasks',:action=>"add_relative_tasks",:as=>"add_relative_tasks"
        get 'show_steps',:action=>"show_steps",:as=>"show_steps"
        match 'delete_step/:step_id', :action=>"delete_step", :as=>"delete_step"
        match 'destroy_detail_step/:detail_step_id', :action=>"destroy_detail_step", :as=>"destroy_detail_step"
        match 'add_detail_step', :action=>"add_detail_step",:as=>"add_detail_step"
        match "multi_handle_steps" => "testcases#multi_handle_steps", :as=>"multi_handle_steps"
        match  "insert_step/:teststep_id"=> "testcases#insert_step", :as=>"insert_step"
        collection {post :import}
  end

   match 'tasks/:task_id/cancel_related_tc/:testcase_id' => "tasks#cancel_related_tc", :as=> "cancel_related_tc"     
   match 'tasks/:task_id/change_running_status/:testcase_id' => "tasks#change_running_status", :as=> "change_running_status"     
   match "tasks/:task_id/delete_result/:counter/:testcase_id/steps" =>"tasks#delete_steps", :as=>"delete_steps"

  resources :tasks do
          get 'get_relative_testcases', :action=>"get_relative_testcases",:as=>"get_relative_testcases"
          match 'run', :action=>"run",:as=>"run"
          match 'reset', :action=>"reset",:as=>"reset"
          match 'current_result/:counter', :action=>"current_result",:as=>"current_result" 
          match 'current_result/:counter/:testcase_id/steps', :action=>"show_steps", :as=>"show_current_steps"
  end

   match "show_step_detail/:step_detail"=>"tasks#show_step_detail", :as=>"show_step_detail"
   
   match "close_step_detail/:step_id" => "tasks#close_step_detail", :as=>"close_step_detail"
   
   match "show_ajax_result" => "http_result#show_ajax_result", :as=>"show_ajax_result"

   match "search_http" => "http_automations#search_http", :as=>"search_http"
   
   match "url_showslow_period_result" => "result#url_showslow_period_result", :as=>"url_showslow_period_result"

  get "introduction/usinghttp"

  get "introduction/usingfunc"
  
  get "introduction/installation" => "introduction#installation", :as=>"introduction_installation"

  get "http_result/show(/:id)" => "http_result#show"
  
  get "http_result/delete_all" => "http_result#clear_all"
  
  match "http_result/run_http" => "http_result#run_http"
  
  match "show_func_step_result" => "tasks#show_func_step_result", :as=>"show_func_step_result"

  resources :http_automations

  resources :hosts

  resources :remote_machines  do
          get "check",  :action =>"check_machine_situ"
  end

  wiki_root '/wiki'

  get "equip/uploadify"

  get "user_behave/login"

  get "user_behave/logout"

  get "index/index"

  get "index/introduction"
  
  match "search_by_date"=>"url_performances#search_by_date", :as=>"search_by_date"
  
  match "search_by_range_time"=>"url_performances#search_by_range_time", :as=>"search_by_range_time"

  resources :users

 get "user_behave/login" => "user_behave#login", :as=>"login"
 
 post "user_behave/login" => "user_behave#try_login", :as=>"login"
 
 get "user_behave/logout" => "user_behave#logout", :as => "logout"
 
 get "equip/show" => "equip#show"

 match "stop_machine_running_situ/:remote_machine_id" => "remote_machines#stop_machine_running_situ", :as=>"stop_machine_running_situ"

  root :to => 'index#index'

end

app/models/tobject.rb
class Tobject < ActiveRecord::Base
  attr_accessible :attribute_values, :description, :label_attributes, :label_types, :syn_name
end

app/controllers/tobjects_controller.rb
class TobjectsController < ApplicationController
  # GET /tobjects
  # GET /tobjects.json
  def index
    @tobjects = Tobject.order("id DESC").page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tobjects }
    end
  end

  # GET /tobjects/1
  # GET /tobjects/1.json
  def show
    @tobject = Tobject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tobject }
    end
  end

  # GET /tobjects/new
  # GET /tobjects/new.json
  def new
    @tobject = Tobject.new

    respond_to do |format|
            if @tobject.save
      format.html {redirect_to tobjects_path}# new.html.erb
      format.json { render json: @tobject }
      end
    end
  end

  # GET /tobjects/1/edit
  def edit
    @tobject = Tobject.find(params[:id])
  end

  # POST /tobjects
  # POST /tobjects.json
  def create
    @tobject = Tobject.new(params[:tobject])

    respond_to do |format|
      if @tobject.save
        format.html { redirect_to @tobject, notice: 'Tobject was successfully created.' }
        format.json { render json: @tobject, status: :created, location: @tobject }
      else
        format.html { render action: "new" }
        format.json { render json: @tobject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tobjects/1
  # PUT /tobjects/1.json
  def update
    @tobject = Tobject.find(params[:id])

    respond_to do |format|
      if @tobject.update_attributes(params[:tobject])
        format.html { redirect_to @tobject, notice: 'Tobject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tobject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tobjects/1
  # DELETE /tobjects/1.json
  def destroy
    @tobject = Tobject.find(params[:id])
    @tobject.destroy

    respond_to do |format|
      format.html { redirect_to tobjects_url }
      format.json { head :no_content }
    end
  end
  
  
  def get_refer_objs
          @refer = params[:refered]
          if @refer == "all"
                  @tobjects = Tobject.page(params[:page])
         elsif @refer == "search"
                 @tobjects = Tobject.where("syn_name like '%#{params["search-info"]}%'").page(params[:page])
         else
                @tobjects = Tobject.where("syn_name like '%#{params[:refered]}%'").page(params[:page])
          end
  end

end

app/helpers/tobjects_helper.rb
module TobjectsHelper
end

app/views/tobjects/_form.html.erb
<%= form_for(@tobject) do |f| %>
  <% if @tobject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tobject.errors.count, "error") %> prohibited this tobject from being saved:</h2>

      <ul>
      <% @tobject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :syn_name %><br />
    <%= f.text_field :syn_name %>
  </div>
  <div class="field">
    <%= f.label :label_types %><br />
    <%= f.text_field :label_types %>
  </div>
  <div class="field">
    <%= f.label :label_attributes %><br />
    <%= f.text_field :label_attributes %>
  </div>
  <div class="field">
    <%= f.label :attribute_values %><br />
    <%= f.text_field :attribute_values %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tobjects/_header.html.erb
<div class="hero-unit">
    <div class="container">
    <h1 style="font-family: Comic Sans MS; font-size:35px;color:white">TestObject</h1>
    <br/>
    <p style="font-family:Kaiti;color:white"> 页面元素对象管理</p>
    </div>
</div>

app/views/tobjects/_tobject.html.erb
<% if  !tobject.nil?%>
<tr class="cm15">
    <td><%=best_in_place tobject,:syn_name  , :html_attrs=>{:style=>"width:90px;font-family:Comic Sans MS"}%></td>
    <td><%=best_in_place tobject,:label_types  , :html_attrs=>{:style=>"width:90px;font-family:Comic Sans MS"}%></td>
    <td><%=best_in_place tobject,:label_attributes  , :html_attrs=>{:style=>"width:90px;font-family:Comic Sans MS"}%></td>
    <td><%=best_in_place tobject,:attribute_values  , :html_attrs=>{:style=>"width:90px;font-family:Comic Sans MS"},  :display_with=>lambda{|v| v.gsub(/(.{40})/,"\\1<br/>").html_safe} %></td>
    <td style="font-family:Kaiti"><%=best_in_place tobject,:description  , :html_attrs=>{:style=>"width:90px;font-family:Kaiti"}%></td>
    <td><%= link_to 'Destroy', tobject, method: :delete, data: { confirm: 'Are you sure?' }, :style=>"font-family:Comic Sans MS" %></td>
</tr>
<%end%>

app/views/tobjects/edit.html.erb
<h1>Editing tobject</h1>

<%= render 'form' %>

<%= link_to 'Show', @tobject %> |
<%= link_to 'Back', tobjects_path %>

app/views/tobjects/get_refer_objs.js.erb
$("#test_objects").html("<%=j render  partial: 'tobject', collection: @tobjects%>");
$("#all").removeAttr("class");
$("#pre").removeAttr("class");
$("#uat").removeAttr("class");
$("#sit").removeAttr("class");
$("#search").removeAttr("class");
$("#<%= @refer%>").addClass("active");
$("#kaminari_ajax").html('<%=j paginate @tobjects , :remote=>true%>');

app/views/tobjects/index.html.erb
<%= render 'header'%>

<div class="container">
    <div class="thumbnail">
                    <br/>
                    <p class="kt18">元素属性添加说明：</p>
                    <p class="kt18">需要多重定位的元素，需要使用‘>’分割符。如 <font class="comic">frame>a, :id>:class, abc>cde</font></p>
                    <p class="kt18"></p>
                    <p class="kt18">添加测试元素对象点击<%= link_to '这里' ,new_tobject_path%></p>
    <%= form_tag(get_refer_objs_path(:refered=>"search"),:remote=>true)  do %>
       <p class="kt18">搜索：<input type="text" id="search-info" name="search-info" style="font-family:Comic Sans MS"/>
           &nbsp;<input type="submit" class="btn btn-primary" value="确定"  style="font-family:Kaiti"/></p> 
    <% end %>
    </div>
</div>
<br/>



<br/>
<div class="container">
    <div class="thumbnail" style="padding:0">
        
            <ul class="nav nav-pills">
                <li class="active"  id="all">
                    <%= link_to "All Objects" , get_refer_objs_path(:refered=>"all") ,:style=>"font-family: Comic Sans MS", :remote=>true%>
                </li>
                <li id="pre">
                    <%= link_to "Pre Objects" , get_refer_objs_path(:refered=>"pre") ,:style=>"font-family: Comic Sans MS", :remote=>true%>
                </li>
                <li id="uat">
                  <%= link_to "Uat Objects" , get_refer_objs_path(:refered=>"uat") ,:style=>"font-family: Comic Sans MS", :remote=>true%>
                </li>
                <li id="sit">
                    <%= link_to "Sit Objects" , get_refer_objs_path(:refered=>"sit") ,:style=>"font-family: Comic Sans MS", :remote=>true%>
                </li>
                <li id="search">
                    <%= link_to "Search Result", "#",:style=>"font-family: Comic Sans MS", :disable=>"true"%>
                </li>
            </ul>
<div  id="kaminari_ajax"   style="font-family: Comic Sans MS; padding-left: 10px"><%= paginate @tobjects %></div>        
<table class="table">
  <tr>
    <th  style="font-family: Comic Sans MS; font-size:16px;">Name</th>
    <th  style="font-family: Comic Sans MS; font-size:16px;">Types</th>
    <th  style="font-family: Comic Sans MS; font-size:16px;">Attributes</th>
    <th  style="font-family: Comic Sans MS; font-size:16px;">Values</th>
    <th  style="font-family: Comic Sans MS; font-size:16px;">Description</th>
    <th></th>
  </tr>

    <tbody id="test_objects">
        <%= render partial: 'tobject', collection: @tobjects%>
    </tbody>
</table>
</div>
</div>
<br />

app/views/tobjects/new.html.erb
<h1>New tobject</h1>

<%= render 'form' %>

<%= link_to 'Back', tobjects_path %>

app/views/tobjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Syn name:</b>
  <%= @tobject.syn_name %>
</p>

<p>
  <b>Label types:</b>
  <%= @tobject.label_types %>
</p>

<p>
  <b>Label attributes:</b>
  <%= @tobject.label_attributes %>
</p>

<p>
  <b>Attribute values:</b>
  <%= @tobject.attribute_values %>
</p>

<p>
  <b>Description:</b>
  <%= @tobject.description %>
</p>


<%= link_to 'Edit', edit_tobject_path(@tobject) %> |
<%= link_to 'Back', tobjects_path %>